language: scala
sudo: false
scala:
- 2.11.8
- 2.12.4
jdk:
- oraclejdk8
script: "./travis.sh"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt"
env:
  global:
  - secure: nKkg4O0n/gnaf4Ql3kdXiy8WVIYsC0If1UaR8x7ynVHxRA8UUZvCppyxtZsDKOq8i5HwY6tPqFJ8Lrge3b1ZUdpVYY3aBvfqnKssLN2hNzvpL17ZpHGMlfNDElHC0RehSwXmYma3478DPvv0+z3CJajXq/rwve/oF8lb+euRFu4KumLrfP4mm5mk8VJ8z2st8BQ1CJFIUc19Jq4XmAAs8nsUsBTUtzXa7GweZXb9ksPvzE2JqbwnEKaAWRPxZpajgn/V8Yvxy9w0t/hoZ3xWB0wbK1jLUKBHj6THO/db93Zm/VK12YHHJPf/mkQxte8qyo5+IA2T99J2cd+usLl5Na6Bf6p/DYmeAyx2Kn05oKPkwJ80tmj22tpjsmq4wBL6+XWwsKiQmKWldj23IBsztumAn1Xx2MnHDx4nTI5V72l/VOC1IivXrh6phTrmOQhj/0gFk2pah0GlLM4jDOVObMIK6QEEoRI61Jf+ZnydMeHHr2tAt0boTvS54Q4DHOR67PQP/KZDoHFr4iliPQqwsoRn+EMiyBxkhzYCoQhHyxutiY4dBX663MOjf6OPDOe7SWAP8q1wlYgrngeAcaMKmTmI2ka8KPW0jMOVVij+DD7FC7F0YZ3G9dK4+qcZ3deLHht1YxMCERxAVssON+Q6krlpgepXxZ8bYI0kpkbLVwg=
  - secure: h5DkywPsj/cBdAEYgqNkCm00t+OFOi0abDHjmwJlW1IcUccRJKi/gjvlpcydCzocL6djv2WW63nt0ldtASN+5XkOJUsseEuDGRogRJDGsHvuHMzRTNKdEa47hElmj/iuSWFPH2XOX8DXJTzLcbPgMW4A8BBH8SnpIzEkbvV6J21b8yUTAmcayIHQh+rC4h7Sr42wQIg1Tf41jD+HTvNwHq+RW2gc8kTFLG78tFlOlLrklCYlwjxcfd+l/sWfycvqcpvnRWtDQpSFLFiaiY8yz1HzJt1DbkPVxcE4MQO0VQAXeqXaeqqEGtMc5Xf6vS9X5h9F5xwPS+r9BKHb42SdcpukhuRakoCQBr8RnhhbvTxKI1qTS87p8RJ2GHZSX8ZABMyxTK29YdH6s4GkxxqdkMmGxO3Zcsz7PuL77ziFWaL8ozEpb71JDkKRXreLYyxH11edJgJem7OoHZKiMboq17C2RaQk6/aRWEvMstW9xDoHeH/f+itv6Fh282s5pmQ/3NlqWZUgIOQhpY9h5fRNzjUtXatIJdVRz30pSVvQRjhS2Awvq/QDmncWMCzortKq5wLnyefj8weDRBOJ2xOJr2+XibB6y+WOAte1L4kzYKsGLCBrioxagO/wKN88iWE4ohsaoC+njH1i0YLO1nyk1DX5M1QAdO1g63KFZb9z1LM=
